import os
import sys
import shutil
import pandas as pd
from datetime import datetime, timezone

# ==========================================
# PATH CONFIGURATION
# ==========================================
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../'))

DAILY_LOGS_DIR = os.path.join(PROJECT_ROOT, "data", "daily_logs")
TRAINING_SETS_DIR = os.path.join(PROJECT_ROOT, "data", "training_sets")

CURRENT_DATASET_PATH = os.path.join(TRAINING_SETS_DIR, "dataset_v_current.csv")
BACKUP_DATASET_PATH = os.path.join(TRAINING_SETS_DIR, "dataset_v_current_backup.csv")

def merge_data():
    print("="*60)
    print("STEP 3.1: MERGING NEW LOG DATA INTO TRAINING DATASET")
    print("="*60)
    
    # 1. Find today's log file (Generated by realtime_defender.py)
    today_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')
    daily_log_path = os.path.join(DAILY_LOGS_DIR, f"log_{today_str}.csv")
    
    if not os.path.exists(daily_log_path):
        print(f"ERROR: Cannot find today's log file at: {daily_log_path}")
        sys.exit(1)
        
    print(f"Found today's log: log_{today_str}.csv")
    df_daily = pd.read_csv(daily_log_path)
    print(f"   -> Number of collected requests today: {len(df_daily):,} rows")
    
    # 2. Read current dataset (Snowball file)
    if not os.path.exists(CURRENT_DATASET_PATH):
        print(f"ERROR: Cannot find current dataset at: {CURRENT_DATASET_PATH}")
        sys.exit(1)
        
    print("\nReading current Master Dataset (Snowball)...")
    df_current = pd.read_csv(CURRENT_DATASET_PATH)
    print(f"   -> Current size: {len(df_current):,} rows")
    
    # 3. Create a Backup before manipulating data
    print("\nCreating backup to prevent data loss...")
    shutil.copy2(CURRENT_DATASET_PATH, BACKUP_DATASET_PATH)
    print(f"   -> Backup created at: {BACKUP_DATASET_PATH}")
    
    # 4. Merge data (Snowballing)
    print("\nMerging data (Concat)...")
    df_new = pd.concat([df_current, df_daily], ignore_index=True)
    
    # Cleanup: Ensure no duplicate logs if the script is run multiple times a day
    original_len = len(df_new)
    if 'request_id' in df_new.columns:
        df_new = df_new.drop_duplicates(subset=['request_id'], keep='last')
        
    dupe_count = original_len - len(df_new)
    if dupe_count > 0:
        print(f"   -> Removed {dupe_count:,} duplicated rows.")
        
    print(f"Merge successful! Total accumulated dataset size: {len(df_new):,} rows")

    # Optional: Print label statistics
    if 'label' in df_new.columns:
        labels = df_new['label'].value_counts()
        print(f"\nLABEL STATISTICS IN NEW DATASET:")
        print(f"   Normal (0): {labels.get(0, 0):,}")
        print(f"   Attack (1): {labels.get(1, 0):,}")

    # 5. OVERWRITE CURRENT FILE
    # This is crucial for creating the accumulated learning effect over time
    df_new.to_csv(CURRENT_DATASET_PATH, index=False)
    print(f"\nOVERWRITTEN accumulated Dataset to:\n   {CURRENT_DATASET_PATH}")

if __name__ == "__main__":
    merge_data()