import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from fpdf import FPDF
from datetime import datetime, timezone
import subprocess
import platform

# ==========================================
# PATH CONFIGURATION
# ==========================================
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

TODAY_STR_DB = datetime.now(timezone.utc).strftime('%Y-%m-%d')
TODAY_STR_FOLDER = datetime.now(timezone.utc).strftime('%d-%m-%Y')

INPUT_CSV = os.path.join(PROJECT_ROOT, "data", "daily_logs", f"log_{TODAY_STR_DB}.csv")
REPORT_DIR = os.path.join(PROJECT_ROOT, "reports", TODAY_STR_FOLDER)
IMAGES_DIR = os.path.join(REPORT_DIR, "images")
PDF_DIR = os.path.join(REPORT_DIR, "pdf")

PDF_OUTPUT_PATH = os.path.join(PDF_DIR, f"Security_Report_{TODAY_STR_FOLDER.replace('-', '_')}.pdf")

# ==========================================
# ENTERPRISE PDF GENERATOR CLASS
# ==========================================
class PDFReport(FPDF):
    def header(self):
        # Corporate Dark Navy Header
        self.set_fill_color(22, 36, 71)
        self.rect(0, 0, 210, 32, 'F')
        
        self.set_y(10)
        self.set_font('helvetica', 'B', 18)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, 'DAILY SECURITY & TRAFFIC REPORT', border=0, align='C', new_x="LMARGIN", new_y="NEXT")
        
        self.set_font('helvetica', 'I', 11)
        self.set_text_color(200, 210, 220)
        self.cell(0, 8, f'Date: {TODAY_STR_FOLDER} | Generated by SP26IA04', border=0, align='C', new_x="LMARGIN", new_y="NEXT")
        self.ln(18)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Confidential & Internal Use Only - SP26IA04', border=0, align='C', new_x="RIGHT", new_y="TOP")

    def chapter_title(self, title):
        self.set_font('helvetica', 'B', 14)
        self.set_fill_color(240, 242, 245)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, f"  {title}", border=0, align='L', fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def chapter_body(self, text):
        self.set_font('helvetica', '', 11)
        self.set_text_color(52, 73, 94)
        self.multi_cell(0, 6, text)
        self.ln(4)
        
    def bullet_point(self, label, value):
        self.set_font('helvetica', 'B', 11)
        self.set_text_color(44, 62, 80)
        self.cell(70, 6, f"{label}:", border=0, align='L', new_x="RIGHT", new_y="TOP")
        self.set_font('helvetica', '', 11)
        self.set_text_color(52, 73, 94)
        self.cell(0, 6, str(value), border=0, align='L', new_x="LMARGIN", new_y="NEXT")

# ==========================================
# MAIN PROCESSING FUNCTIONS
# ==========================================
def setup_directories():
    print(f"[INFO] Preparing report directories for {TODAY_STR_FOLDER}...")
    os.makedirs(IMAGES_DIR, exist_ok=True)
    os.makedirs(PDF_DIR, exist_ok=True)

def generate_report():
    if not os.path.exists(INPUT_CSV):
        print(f"[ERROR] Today's log file not found at {INPUT_CSV}")
        print("[INFO] Please run the traffic generator first.")
        sys.exit(1)

    print("[INFO] Reading and analyzing data...")
    df = pd.read_csv(INPUT_CSV)
    
    df['@timestamp'] = pd.to_datetime(df['@timestamp'])
    df['status'] = pd.to_numeric(df['status'], errors='coerce').fillna(200)
    df['label'] = pd.to_numeric(df['label'], errors='coerce').fillna(0).astype(int)
    
    # ------------------------------------------
    # 1. CALCULATE METRICS
    # ------------------------------------------
    total_reqs = len(df)
    attack_reqs = df['label'].sum()
    normal_reqs = total_reqs - attack_reqs
    
    error_reqs = len(df[df['status'] >= 400])
    error_rate = (error_reqs / total_reqs) * 100 if total_reqs > 0 else 0
    
    top_endpoints = df['path_normalized'].value_counts().head(5)
    top_endpoints_text = "\n".join([f"    - {path}: {count:,} requests" for path, count in top_endpoints.items()])

    attack_df = df[df['label'] == 1]
    top_ips = attack_df['remote_ip'].value_counts().head(5)
    top_ips_text = "\n".join([f"    - {ip}: {count:,} malicious requests" for ip, count in top_ips.items()])
    if not top_ips_text:
        top_ips_text = "    - No significant attacks detected originating from a single IP today."

    df['hour'] = df['@timestamp'].dt.hour
    busiest_hour = df['hour'].mode()[0] if not df.empty else 0

    print("[INFO] Generating charts...")
    sns.set_theme(style="white")

    # ------------------------------------------
    # 2. GENERATE CHARTS
    # ------------------------------------------
    # Chart 1: Traffic Timeline
    plt.figure(figsize=(8, 4))
    hourly_traffic = df.groupby('hour').size()
    hourly_traffic.plot(kind='line', marker='o', color='#1f4e78', linewidth=2.5)
    plt.title('Traffic Timeline (Requests / Hour)', fontsize=12, fontweight='bold', color='#2c3e50')
    plt.xlabel('Hour of Day (UTC)', fontsize=10, color='#7f8c8d')
    plt.ylabel('Number of Requests', fontsize=10, color='#7f8c8d')
    plt.xticks(range(0, 24))
    sns.despine()
    plt.tight_layout()
    timeline_img = os.path.join(IMAGES_DIR, 'traffic_timeline.png')
    plt.savefig(timeline_img, dpi=300)
    plt.close()

    # Chart 2: HTTP Status Codes (UPGRADED WITH LEGEND)
    plt.figure(figsize=(8, 5)) # Wider figure to fit the legend
    status_counts = df['status'].value_counts()
    
    # Semantic colors for common HTTP statuses
    semantic_colors = {
        200: '#27ae60', 201: '#2ecc71', # Success (Greens)
        400: '#f39c12', 401: '#e67e22', 403: '#d35400', 404: '#8e44ad', # Client Errors (Oranges/Purple)
        429: '#c0392b', # Rate Limit (Red)
        499: '#7f8c8d', # Client Closed (Grey)
        500: '#c0392b', 502: '#34495e', 503: '#2c3e50', 504: '#000000' # Server Errors (Dark Reds/Black)
    }
    
    # Assign colors dynamically based on available statuses
    palette = sns.color_palette("husl", len(status_counts))
    colors = [semantic_colors.get(int(s), palette[i % len(palette)]) for i, s in enumerate(status_counts.index)]
    
    wedges, texts, autotexts = plt.pie(
        status_counts.values, 
        autopct='', # Hide percentages from pie slices to keep it clean
        colors=colors, 
        startangle=90,
        wedgeprops=dict(width=0.4, edgecolor='w') # Make it a donut chart for a modern look
    )
    
    # Prepare custom legend labels with percentages and exact counts
    legend_labels = [f"HTTP {int(status)} - {count:,} reqs ({count/total_reqs*100:.1f}%)" 
                     for status, count in zip(status_counts.index, status_counts.values)]
    
    plt.legend(wedges, legend_labels, title="HTTP Status Codes", 
               loc="center left", bbox_to_anchor=(1, 0, 0.5, 1), fontsize=10, title_fontsize=11)

    plt.title('HTTP Status Code Distribution', fontsize=12, fontweight='bold', color='#2c3e50')
    plt.tight_layout()
    status_pie_img = os.path.join(IMAGES_DIR, 'status_pie.png')
    plt.savefig(status_pie_img, dpi=300, transparent=True, bbox_inches='tight')
    plt.close()

    # Chart 3: Top Attacker IPs (Bar chart)
    top_ips_img = None
    if not attack_df.empty:
        plt.figure(figsize=(8, 4))
        sns.barplot(x=top_ips.values, y=top_ips.index, hue=top_ips.index, palette="Reds_r", legend=False)
        plt.title('Top 5 Malicious IP Addresses', fontsize=12, fontweight='bold', color='#2c3e50')
        plt.xlabel('Number of Malicious Requests', fontsize=10, color='#7f8c8d')
        sns.despine()
        plt.tight_layout()
        top_ips_img = os.path.join(IMAGES_DIR, 'top_ips_bar.png')
        plt.savefig(top_ips_img, dpi=300)
        plt.close()

    # ------------------------------------------
    # 3. ASSEMBLE PDF
    # ------------------------------------------
    print("[INFO] Assembling PDF report...")
    pdf = PDFReport()
    
    # PAGE 1: Executive Summary
    pdf.add_page()
    pdf.chapter_title('1. EXECUTIVE SUMMARY')
    
    intro_text = (
        "This document provides an automated, comprehensive daily overview of the API Gateway traffic and security alerts processed by the AI Threat Detection System. "
        "Leveraging advanced machine learning algorithms (LightGBM), the system continuously monitors, analyzes, and mitigates potential threats in real-time, ranging from volumetric DDoS attacks to sophisticated Broken Object Level Authorization (BOLA) attempts.\n\n"
        "The metrics below summarize the overall health, traffic distribution, and security posture of the microservices ecosystem over the past 24 hours. "
        "A low False Positive rate and stable response times indicate optimal system performance."
    )
    pdf.chapter_body(intro_text)
    
    pdf.bullet_point("Total Requests Processed", f"{total_reqs:,}")
    pdf.bullet_point("Normal Traffic (Allowed)", f"{normal_reqs:,} ({(normal_reqs/total_reqs)*100 if total_reqs else 0:.1f}%)")
    pdf.bullet_point("Malicious Traffic (Blocked)", f"{attack_reqs:,} ({(attack_reqs/total_reqs)*100 if total_reqs else 0:.1f}%)")
    pdf.bullet_point("Global Error Rate (4xx/5xx)", f"{error_rate:.2f}%")
    pdf.ln(8)
    
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 10, 'HTTP Status Distribution Overview', border=0, new_x="LMARGIN", new_y="NEXT")
    # Tweak coordinates to accommodate the wider legend chart
    pdf.image(status_pie_img, x=15, w=160)

    # PAGE 2: Traffic Details
    pdf.add_page()
    pdf.chapter_title('2. TRAFFIC DETAILS & ENDPOINT UTILIZATION')
    
    traffic_intro = (
        "This section outlines the traffic patterns observed across the core API infrastructure. "
        "Understanding peak access times and highly utilized endpoints is crucial for capacity planning, resource allocation, and identifying potential system bottlenecks. "
        "Sudden, uncharacteristic spikes in traffic may also correlate with reconnaissance or denial-of-service activities."
    )
    pdf.chapter_body(traffic_intro)
    
    pdf.bullet_point("Peak Hour (Busiest Traffic)", f"{busiest_hour}:00 - {busiest_hour}:59 UTC")
    pdf.ln(4)
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 6, "Top 5 Most Accessed Endpoints:", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.chapter_body(top_endpoints_text)
    
    pdf.ln(5)
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Hourly Traffic Timeline', border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.image(timeline_img, x=15, w=180)

    # PAGE 3: Security & AI
    pdf.add_page()
    pdf.chapter_title('3. SECURITY & THREAT ANALYSIS')
    
    sec_intro = (
        "Our underlying Machine Learning model rigorously analyzed all incoming payloads, request metadata, and behavioral patterns. "
        "By correlating extracted features (such as sliding-window request frequencies and double-decoded path syntaxes) against known attack signatures, "
        f"the AI successfully isolated and neutralized {attack_reqs:,} high-risk requests today.\n\n"
        "Immediate automated responses (e.g., dynamic rate limiting, nftables blacklisting) were executed for critical threats. "
        "Below is the detailed breakdown of the most aggressive source IP addresses that warrant continuous monitoring or permanent network-level bans."
    )
    pdf.chapter_body(sec_intro)
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(0, 6, "Top 5 Most Aggressive IPs (Recommended for Firewall Blacklist):", border=0, new_x="LMARGIN", new_y="NEXT")
    pdf.chapter_body(top_ips_text)
    
    if top_ips_img:
        pdf.ln(5)
        pdf.set_font('helvetica', 'B', 12)
        pdf.cell(0, 10, 'Malicious Traffic Origin', border=0, new_x="LMARGIN", new_y="NEXT")
        pdf.image(top_ips_img, x=15, w=180)

    pdf.output(PDF_OUTPUT_PATH)
    print(f"[SUCCESS] Report generated successfully at:\n          -> {PDF_OUTPUT_PATH}")

    # ------------------------------------------
    # 4. AUTO-OPEN PDF
    # ------------------------------------------
    try:
        if platform.system() == 'Darwin':
            subprocess.call(('open', PDF_OUTPUT_PATH))
        elif platform.system() == 'Windows':
            os.startfile(PDF_OUTPUT_PATH)
        else:
            subprocess.call(('xdg-open', PDF_OUTPUT_PATH))
        print("[INFO] Opening PDF viewer...")
    except Exception:
        print(f"[WARNING] Could not open PDF automatically. Please open it manually at {PDF_OUTPUT_PATH}")

if __name__ == "__main__":
    print("="*60)
    print("STARTING DAILY REPORT GENERATION...")
    print("="*60)
    setup_directories()
    generate_report()